# CMake generated Testfile for 
# Source directory: /home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less
# Build directory: /home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/lib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(LESS_benchmark_cat_252_192 "LESS_benchmark_cat_252_192")
set_tests_properties(LESS_benchmark_cat_252_192 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;85;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_test_cat_252_192 "LESS_test_cat_252_192")
set_tests_properties(LESS_test_cat_252_192 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;92;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_nist_cat_252_192 "LESS_nist_cat_252_192")
set_tests_properties(LESS_nist_cat_252_192 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;100;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_benchmark_cat_252_68 "LESS_benchmark_cat_252_68")
set_tests_properties(LESS_benchmark_cat_252_68 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;85;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_test_cat_252_68 "LESS_test_cat_252_68")
set_tests_properties(LESS_test_cat_252_68 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;92;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_nist_cat_252_68 "LESS_nist_cat_252_68")
set_tests_properties(LESS_nist_cat_252_68 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;100;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_benchmark_cat_252_45 "LESS_benchmark_cat_252_45")
set_tests_properties(LESS_benchmark_cat_252_45 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;85;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_test_cat_252_45 "LESS_test_cat_252_45")
set_tests_properties(LESS_test_cat_252_45 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;92;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_nist_cat_252_45 "LESS_nist_cat_252_45")
set_tests_properties(LESS_nist_cat_252_45 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;100;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_benchmark_cat_400_220 "LESS_benchmark_cat_400_220")
set_tests_properties(LESS_benchmark_cat_400_220 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;85;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_test_cat_400_220 "LESS_test_cat_400_220")
set_tests_properties(LESS_test_cat_400_220 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;92;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_nist_cat_400_220 "LESS_nist_cat_400_220")
set_tests_properties(LESS_nist_cat_400_220 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;100;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_benchmark_cat_400_102 "LESS_benchmark_cat_400_102")
set_tests_properties(LESS_benchmark_cat_400_102 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;85;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_test_cat_400_102 "LESS_test_cat_400_102")
set_tests_properties(LESS_test_cat_400_102 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;92;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_nist_cat_400_102 "LESS_nist_cat_400_102")
set_tests_properties(LESS_nist_cat_400_102 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;100;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_benchmark_cat_548_345 "LESS_benchmark_cat_548_345")
set_tests_properties(LESS_benchmark_cat_548_345 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;85;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_test_cat_548_345 "LESS_test_cat_548_345")
set_tests_properties(LESS_test_cat_548_345 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;92;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_nist_cat_548_345 "LESS_nist_cat_548_345")
set_tests_properties(LESS_nist_cat_548_345 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;100;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_benchmark_cat_548_137 "LESS_benchmark_cat_548_137")
set_tests_properties(LESS_benchmark_cat_548_137 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;85;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_test_cat_548_137 "LESS_test_cat_548_137")
set_tests_properties(LESS_test_cat_548_137 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;92;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
add_test(LESS_nist_cat_548_137 "LESS_nist_cat_548_137")
set_tests_properties(LESS_nist_cat_548_137 PROPERTIES  _BACKTRACE_TRIPLES "/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;100;add_test;/home/damya/Documents/Cours_Télécom/prim_P2/faultycross/fault_less/CMakeLists.txt;0;")
